// <auto-generated />
namespace BundleGames.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addgametocardmodeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addgametocardmodeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "202008171543198_addgametocardmodeladded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
