// <auto-generated />
namespace BundleGames.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _26julydone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26julydone));
        
        string IMigrationMetadata.Id
        {
            get { return "202007261111162_26julydone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
